micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:secrettext@@@adssssssssssdasadsdasas}"'

  application:
    name: test
netty:
  default:
    allocator:
      max-order: 3
